Update _config.ts markdownemoji
Currently it is giving this error

SyntaxError: The requested module 'https://jspm.dev/markdown-it-emoji' does not provide an export named 'markdownEmoji' at file:///Users/ca/dev/denissb.github.io/_config.ts:9:10
    at async createSite (https://deno.land/x/lume@v1.18.4/cli/run.ts:50:17)
    at async build (https://deno.land/x/lume@v1.18.4/cli/build.ts:33:16)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async (https://deno.land/x/lume@v1.18.4/cli.ts:135:3)